project_id = "otfrxwmjefcgooqwxdwe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600

[auth.email]
enabled = true
double_confirm_changes = true
max_frequency = "1s"

[db]
shadow_port = 54320
major_version = 15

[functions.aws-trigger]
verify_jwt = false

[functions.github-trigger]
verify_jwt = false